[build-system]
requires = [ "setuptools>=41", "wheel", "setuptools-git-versioning<2", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools-git-versioning]
enabled = true

[project]
name = "pycwb"
keywords=['ligo', 'physics', 'gravity', 'signal processing', 'gravitational waves', 'cwb', 'coherent wave burst']
requires-python = ">=3.8"
dynamic = ["version", "readme", "description", "authors", "dependencies"]

[tool.setuptools_scm]
write_to = "pycwb/_version.py"